Cr 4016
codefresh-io/argocd-autopilot pull request #3
Opened 2021-04-21 14:41 UTC by oren-codefresh

2021-04-21 14:43 UTC, noam-codefresh commented on cmd/commands/app.go
> +		Use:   "list [ENV_NAME]",
change all references from `env` to `project`

2021-04-21 14:54 UTC, roi-codefresh requested changes

2021-04-21 14:54 UTC, roi-codefresh commented on cmd/commands/app.go
> +type (
move inside upper `type` block

2021-04-21 14:54 UTC, roi-codefresh commented on cmd/commands/app.go
> +		Short: "List all applications in an environment",
this is no longer called an environment, rename to project

2021-04-21 14:54 UTC, roi-codefresh commented on cmd/commands/app.go
> +# Get list of applications from a remote repository
`List installed applications in a specific project`

2021-04-21 14:54 UTC, roi-codefresh commented on cmd/commands/app.go
> +	log.G().Infof("using revision: \"%s\", installation path: \"%s\"", opts.CloneOptions.Revision, opts.CloneOptions.RepoRoot)
change `opts.CloneOptions.RepoRoot` to `opts.FS.Root()` it's prettier

2021-04-21 14:54 UTC, roi-codefresh commented on cmd/commands/app.go
> +	matches, err := billyUtils.Glob(opts.FS, fmt.Sprintf("/kustomize/*/overlays/%s", opts.ProjectName))
I would check for the `config.json` because that's what actually determines if an argocd app is generated or not

2021-04-21 14:54 UTC, roi-codefresh commented on cmd/commands/app.go
> +		log.G().Info(strings.Split(appName, "/")[2])
I would have liked to see something more than just an app name, but maybe that's enough for now

2021-04-21 14:55 UTC, roi-codefresh commented
ADD TESTS!

2021-04-22 06:11 UTC, roi-codefresh commented on cmd/commands/app.go
> +		log.G().Info(strings.Split(appName, "/")[2])
for sure

2021-04-26 08:31 UTC, merged